service: flambe-example

custom: 
  flambe:
    regex:
      - hello
      - /good.*/
    memorySize: 128
      
  webpack:
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2 
  package:
    individually: true

functions:
  hello:
    handler: handlers.hello
    timeout: 10
    flambe:
      rate: 'rate(3 minutes)'

  goodbye:
    handler: handlers.goodbye
    flambe:
      wrapper: customWrapper.default
      input:
        custom: 'property'

  ignored:
    handler: handlers.goodbye # re-used for brevity

plugins:
  - serverless-plugin-flambe
  - serverless-webpack