service: pilot_light-example

custom: 
  pilot_light:
    - hello
    - /good.*/
      
  webpack:
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2 
  package:
    individually: true

functions:
  hello:
    handler: handlers.hello
    timeout: 10
    pilot_light:
      rate: 'rate(3 minutes)'

  goodbye:
    handler: handlers.goodbye
    pilot_light:
      wrapper: customWrapper.default
      input:
        custom: 'property'

  ignored:
    handler: handlers.goodbye # re-used for brevity

plugins:
  - serverless-plugin-pilot-light
  - serverless-webpack